language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
script: "./build.sh"
#env:
#  global:
#  - secure: eBsPr3LHaQIv7odvp2q1q9jVekqxZkAas0kafKyscWbPyRjgMkdr3snshyruvPKtTZyrhxUI5wCBZpJIaR2YO2xY8AjpO4FJ85z4HfZUuq1UnEkIQDytUpSUJ3rVL6SlMlf81hGNV1OHqWMEKen76jQXB5N7c/Sp6zP1rU2kmAE=
